### ISSUE TITLE
Spurious text detections with images from comics

### ISSUE THREAD

**Issue by 0x41337** [robertknight/ocrs#99]
Hi, thanks for the project and your hard work on it, I was doing some tests just out of curiosity, but I encountered some problems when testing images like mangas or manwuas (Comics in general).

![](https://github.com/user-attachments/assets/830d6af4-859e-4985-8280-c4d5f0c7809f)

As you see it detects "letters"? I'm not sure, but the output is pretty messy:

```
W
HAA
4
UN...
+n3E39
I
13
N
B
a
HA
E
SATHIS
FOR
REALS
H
I 5
N
HIH
h
H
O
EE
mN
2y
C
WHY.
1
M
O
AM D...!
3
M
PARAMA AAN
h
N

```

I would like to ask you for help, I am not an expert in this area, just curious. I would like to know if I need to treat the image with some filter before passing it to OCR. To get the lines and texts only, not the drawings or drawing vertices.

**Comment by robertknight** [comment]
The current text detection model is indeed prone to spurious detections with images that contain line art. You can visualize the detection predictions using `ocrs image.png --text-map` (generates probability image) and `ocrs image.png --text-mask` (shows binary mask after threshold is applied).

For this image the map / mask look like:

<img src="https://github.com/user-attachments/assets/ba28724a-c5ef-433a-9507-1c727db019b3" width="300">
<img src="https://github.com/user-attachments/assets/91a591e1-97b0-4562-8b95-e6718f035e4b" width="300">

From these I can see that part of the problem is just that the detection threshold is quite low. Making this configurable would be useful.

The bigger issue though is that the training data for the [models](https://github.com/robertknight/ocrs-models) doesn't have enough line art content to learn from. Most of the images in the current dataset are photos. One way to improve the outputs would be to fine tune the models on comic book images. Maybe using a dataset like [COMICS Text+](https://github.com/gsoykan/comics_text_plus).

If there is already a good comic text detection model available somewhere in Python then it may be possible to export that to ONNX and then [convert it](https://github.com/robertknight/rten?tab=readme-ov-file#converting-onnx-models) for use in Rust.
